apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommece-admin
        image: containerRegistryGrupo1.azurecr.io/images/ecommerce-admin:0.0.1
        ports:
        - containerPort: 3000
      - name: ecommerce-store
        image: containerRegistryGrupo1.azurecr.io/images/ecommerce-store:0.0.1
        ports:
        - containerPort: 3001
