apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommece-admin-service
spec:
  ingressClassName: ecommerceCluster.kubernetes.azure.com
  rules:
  - host: 10.0.0.10
    http:
      paths:
      - backend:
          service:
            name: ecommece-admin-service
            port:
              number: 3000
        path: /admin
        pathType: Prefix
      - backend:
          service:
            name: ecommerce-store-service
            port:
              number: 3001
        path: /
        pathType: Prefix