apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
